### ISSUE TITLE
Support cohttp 2.0.0

### ISSUE THREAD

**Issue by gtrak** [brendanlong/sentry-ocaml#16]
Currently it doesn't build with 2.0.0.

```
# File "src/dune", line 3, characters 33-45:
# 3 |   (libraries async_kernel atdgen cohttp.async core_kernel hex json-derivers uri uuidm re2 yojson)
#                                      ^^^^^^^^^^^^
```

**Comment by brendanlong** [comment]
This should already be enforced by the .opam file: https://github.com/brendanlong/sentry-ocaml/blob/master/sentry.opam#L13

The tricky thing is that I don't think I can support both at the same time, since the library name changes and there are some minor changes to the API.

**Comment by gtrak** [comment]
Is it worth doing something like https://github.com/janestreet/ppx_optcomp

Does dune have a similar facility?

**Comment by brendanlong** [comment]
There's probably some way we could this with Dune's "the dune file is an OCaml file" mode, but.. yikes.
If you think it's worth it, we could just switch to require cohttp>=2.0 though?

**Comment by gtrak** [comment]
I'll think about it more, this is motivated by the TLS default override we made internally and the suspicion that a newer version of cohttp might be better, but I think I should spend more time looking into that.
