### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [brendanlong/sentry-ocaml#2]
Hi!

I was lately also thinking whether it would make sense to submit our logs to Sentry (also using Async, so very convenient), so I am happy I stumbled over this library. But it is missing any kind of license, so it is a bit problematic to use and to contribute.

Could you please pick some license? Thanks a lot!

**Comment by brendanlong** [comment]
Sorry about that, I must have forgot to add this. Commit c5e438c381584b45f021abc1b5d1653ab24418f1 adds one (public domain).

**Comment by brendanlong** [comment]
FYI, I'm having trouble getting nice Async backtraces (see #1). If you have ideas for improving that let me know, or open a pull request.

**Comment by Leonidas-from-XIV** [comment]
Thanks!

From what I see it does sound like the best idea to patch `Error` with support for the `raw_backtrace`. I don't know if I have time to write these patches but I can see if I can fit that in.

What I am a confused about is that `raw_backtrace` can only be sensibly used its exception handler, so I am worried that storing it in `Error.t` wouldn't work since it would point to outdated/invalid data.

**Comment by brendanlong** [comment]
I created this issue to get the data we need from Async: https://github.com/janestreet/async_kernel/issues/10

`raw_backtrace` can be safely passed around. The annoying part is that you can only safely call `Printexc.get_raw_backtrace` in an exception handler (before calling any other function).
